# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Cronograma"
url = "cronograma"
weight = 2

[[main]]
name = "Palestras"
url = "palestras"
weight = 3

[[main]]
name = "FAQ"
url = "faq"
weight = 4

# footer menu left
[[footer_left]]
name = "Nosso Grupo"
url = "grupo"

[[footer_left]]
name = "Edições anteriores"
url = "ed-anteriores"

# footer menu middle
[[footer_middle]]
name = "Cronograma"
url = "cronograma"

[[footer_middle]]
name = "Palestras"
url = "palestras"

[[footer_middle]]
name = "Participantes Selecionados"
url = "participantes"

[[footer_right]]
name = "FAQ"
url = "faq"