baseURL: https://wpdb2022.netlify.app/
title: V Workshop Python para Dados Biológicos
theme: bigspring-light
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
